services:
  db:
    image: postgres:16.1
    container_name: java-shareit
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d shareit"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: unless-stopped